name: Run Tests with Docker image

on:
  pull_request_target:
    # opened/synchronize: run CI on PRs in internal repos without requiring a label
    # labeled: run CI on public repo PRs only after the 'safe-to-test' label is applied
    types: [labeled, opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'pull_request_target' &&
       (github.repository == 'aqlaboratory/openfold-3' &&
        github.event.action == 'labeled' &&
        github.event.label.name == 'safe-to-test') ||
       (github.repository != 'aqlaboratory/openfold-3'))
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - cuda_base_image_tag: "12.1.1-cudnn8-devel-ubuntu22.04"
            build_mode: "yaml"
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ matrix.cuda_base_image_tag }}
      cancel-in-progress: true
    uses: ./.github/workflows/ci-test-reusable.yml
    with:
      cuda_base_image_tag: ${{ matrix.cuda_base_image_tag }}
      build_mode: ${{ matrix.build_mode }}
    secrets: inherit
